version: 2

updates:
  - package-ecosystem: cargo
    directories:
      - /
      - /fuzz
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      breaking:
        patterns: ["*"]
        update-types: ["major"]
        group-by: dependency-name

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
