//! One-shot hunt: SQL shapes not yet in the campaign. Fail if any oracle is open.
//!
//! Analyst residual (must stay allowed): bare `SELECT` of a masked column,
//! simple `ORDER BY` of one, `SELECT … FETCH FIRST`, and `SELECT *` / `TABLE`.

#![allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use std::collections::{HashMap, HashSet};

use pgmask::analysis::{
    calls_untrusted_function, hostile_join_or_rename_masked, hostile_uses_whole_row,
    is_sql_prepare_or_cursor, is_write_statement, masked_exceeds_outer_projection,
    reads_only_server_metadata, touches_leaky_system_catalog,
};

fn masked() -> HashSet<String> {
    ["email", "name", "phone", "annual_salary", "internal_note"]
        .into_iter()
        .map(str::to_string)
        .collect()
}

fn relations() -> HashMap<String, Vec<String>> {
    let mut m = HashMap::new();
    m.insert(
        "demo.customers".into(),
        vec![
            "id".into(),
            "email".into(),
            "name".into(),
            "phone".into(),
            "city".into(),
            "birth_date".into(),
            "annual_salary".into(),
            "last_ip".into(),
            "account_uuid".into(),
            "internal_note".into(),
            "lookup_key".into(),
        ],
    );
    m.insert(
        "customers".into(),
        vec![
            "id".into(),
            "email".into(),
            "name".into(),
            "phone".into(),
            "city".into(),
        ],
    );
    m
}

fn hostile_refused(sql: &str) -> bool {
    masked_exceeds_outer_projection(sql, &masked())
        || hostile_uses_whole_row(sql, &relations())
        || hostile_join_or_rename_masked(sql, &relations(), &masked())
}

fn any_frontend_refuse(sql: &str) -> bool {
    is_write_statement(sql)
        || is_sql_prepare_or_cursor(sql)
        || calls_untrusted_function(sql)
        || touches_leaky_system_catalog(sql)
        || hostile_refused(sql)
}

#[test]
fn hunt_finds_no_new_oracles() {
    let must_allow = [
        "SELECT email FROM demo.customers",
        "SELECT email, id FROM demo.customers WHERE id = 1",
        "SELECT id FROM demo.customers ORDER BY email",
        "SELECT * FROM demo.customers",
        "TABLE demo.customers",
        "SELECT email FROM demo.customers FETCH FIRST 10 ROWS ONLY",
        "SELECT city FROM demo.customers WHERE city = 'Denver'",
        "SELECT count(*) FROM demo.customers WHERE city = 'Denver'",
        "SELECT email FROM demo.customers WHERE id IN (1, 2)",
        "BEGIN",
        "EXPLAIN SELECT email FROM demo.customers",
        "EXPLAIN SELECT id FROM demo.customers ORDER BY email",
        "SHOW search_path",
        "SELECT DISTINCT email FROM demo.customers",
        "SELECT id FROM demo.customers ORDER BY email NULLS FIRST",
        "SELECT id FROM demo.customers ORDER BY email DESC",
        "TABLE ONLY demo.customers",
        "SELECT t.email FROM demo.customers t",
        r#"SELECT id, count(*) OVER w FROM demo.customers WINDOW w AS (ORDER BY email)"#,
        r#"SELECT id FROM demo.customers ORDER BY email COLLATE "C""#,
        r#"SELECT id FROM demo.customers ORDER BY email USING >"#,
        r#"SELECT id FROM demo.customers ORDER BY email USING OPERATOR(pg_catalog.<)"#,
        "SELECT * FROM information_schema.user_mappings",
        "SELECT * FROM information_schema.foreign_servers",
        "SELECT * FROM information_schema.foreign_tables",
        "SELECT * FROM information_schema.foreign_data_wrappers",
        "SELECT table_name FROM information_schema.tables",
        "SELECT rolname FROM pg_roles",
    ];
    let mut bad = Vec::new();
    for sql in must_allow {
        if hostile_refused(sql) {
            bad.push(format!("OVER-REFUSED analyst SELECT:\n  {sql}"));
        }
    }

    let oracles: &[&str] = &[
        // JSON unique-keys / scalar / value predicates
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON WITH UNIQUE KEYS"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON WITHOUT UNIQUE KEYS"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON SCALAR"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON VALUE"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON SCALAR WITH UNIQUE KEYS"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS NOT JSON WITH UNIQUE KEYS"#,
        r#"SELECT JSON_OBJECT('e': u&"email" WITH UNIQUE KEYS) FROM demo.customers"#,
        r#"SELECT JSON_OBJECT('e': u&"email" ABSENT ON NULL) FROM demo.customers"#,
        r#"SELECT JSON_ARRAY(u&"email" RETURNING jsonb) FROM demo.customers"#,
        r#"SELECT JSON_ARRAY(u&"email" NULL ON NULL) FROM demo.customers"#,
        r#"SELECT json_arrayagg(u&"email" RETURNING jsonb) FROM demo.customers"#,
        r#"SELECT json_objectagg(u&"email": city WITH UNIQUE KEYS) FROM demo.customers"#,
        // substring SIMILAR / overlay / translate family
        r#"SELECT count(*) FROM demo.customers WHERE substring(u&"email" similar '%#"x#"%' escape '#') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE overlay(u&"email" placing 'x' from 1 for 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE translate(u&"email", 'a', 'b') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE replace(u&"email", 'a', 'b') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE reverse(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE repeat(u&"email", 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE ascii(u&"email") = 117"#,
        r#"SELECT count(*) FROM demo.customers WHERE chr(ascii(u&"email")) = 'u'"#,
        r#"SELECT count(*) FROM demo.customers WHERE quote_literal(u&"email") LIKE '%x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE quote_nullable(u&"email") LIKE '%x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE quote_ident(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE strpos(u&"email", '@') = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE substr(u&"email", 1, 1) = 'u'"#,
        r#"SELECT count(*) FROM demo.customers WHERE lpad(u&"email", 10) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE rpad(u&"email", 10) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE ltrim(u&"email", 'u') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE rtrim(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE btrim(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE initcap(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE to_hex(length(u&"email")) = 'c'"#,
        r#"SELECT count(*) FROM demo.customers WHERE octet_length(u&"email") = 5"#,
        r#"SELECT count(*) FROM demo.customers WHERE bit_length(u&"email") = 40"#,
        r#"SELECT count(*) FROM demo.customers WHERE character_length(u&"email") = 5"#,
        r#"SELECT count(*) FROM demo.customers WHERE char_length(u&"email") = 5"#,
        r#"SELECT count(*) FROM demo.customers WHERE get_byte(u&"email"::bytea, 0) = 117"#,
        r#"SELECT count(*) FROM demo.customers WHERE get_bit(u&"email"::bytea, 0) = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE encode(u&"email"::bytea, 'base64') LIKE '%x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE convert(u&"email"::bytea, 'UTF8', 'LATIN1') IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE sha256(u&"email"::bytea) IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE to_tsvector('simple', u&"email") @@ 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" % 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE similarity(u&"email", 'x') > 0.5"#,
        r#"SELECT count(*) FROM demo.customers WHERE levenshtein(u&"email", 'x') < 3"#,
        r#"SELECT count(*) FROM demo.customers WHERE regexp_like(u&"email", 'x')"#,
        r#"SELECT count(*) FROM demo.customers WHERE regexp_count(u&"email", 'x') > 0"#,
        r#"SELECT count(*) FROM demo.customers WHERE regexp_substr(u&"email", 'x') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE regexp_instr(u&"email", 'x') = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE regexp_replace(u&"email", 'x', 'y') = 'y'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" ~~* 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" !~~ 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" !~ 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" !~* 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.~~*) 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS NOT DISTINCT FROM 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"annual_salary" > 100000"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"annual_salary" BETWEEN 1 AND 2"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"phone" LIKE '5%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"name" ILIKE 'a%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"internal_note" IS NULL"#,
        // LATERAL / SRF / VALUES of a masked column
        r#"SELECT count(*) FROM demo.customers, LATERAL (VALUES (u&"email")) v(e) WHERE e = 'x'"#,
        r#"SELECT count(*) FROM demo.customers, LATERAL string_to_table(u&"email", '@') s"#,
        r#"SELECT count(*) FROM demo.customers, LATERAL regexp_split_to_table(u&"email", '@') s"#,
        r#"SELECT * FROM string_to_table((SELECT u&"email" FROM demo.customers LIMIT 1), '@')"#,
        r#"SELECT count(*) FROM demo.customers, unnest(string_to_array(u&"email", '@')) s"#,
        r#"SELECT count(*) FROM demo.customers WHERE string_to_array(u&"email", '@') && ARRAY['x']"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" = ANY(string_to_array('x,y', ','))"#,
        // Window GROUPS / EXCLUDE / FILTER already partly covered
        r#"SELECT id, count(*) OVER (ORDER BY id GROUPS BETWEEN (SELECT count(*) FROM demo.customers t2 WHERE t2.u&"email" = 'x') PRECEDING AND CURRENT ROW) FROM demo.customers"#,
        r#"SELECT id, count(*) OVER (ORDER BY u&"email" GROUPS BETWEEN 1 PRECEDING AND 1 FOLLOWING EXCLUDE CURRENT ROW) FROM demo.customers"#,
        r#"SELECT id, count(*) OVER (ORDER BY id RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE TIES) FROM demo.customers WHERE u&"email" = 'x'"#,
        // JOIN USING mixed, NATURAL variants
        r#"SELECT count(*) FROM demo.customers a JOIN demo.customers b USING (id, u&"email")"#,
        r#"SELECT count(*) FROM demo.customers a NATURAL LEFT JOIN demo.customers b"#,
        r#"SELECT count(*) FROM demo.customers a NATURAL RIGHT JOIN demo.customers b"#,
        r#"SELECT count(*) FROM demo.customers a NATURAL FULL JOIN demo.customers b"#,
        r#"SELECT count(*) FROM demo.customers a INNER JOIN demo.customers b ON a.id = b.id AND a.u&"email" = b.u&"email""#,
        r#"SELECT count(*) FROM demo.customers a CROSS JOIN demo.customers b WHERE a.u&"email" = b.u&"email""#,
        // TABLESAMPLE / ONLY / inheritance
        r#"SELECT count(*) FROM demo.customers TABLESAMPLE SYSTEM (50) REPEATABLE (length(u&"email"))"#,
        r#"SELECT count(*) FROM demo.customers TABLESAMPLE BERNOULLI ((SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'))"#,
        // UNIQUE / MATCH / OVERLAPS (some may fail to parse → fail closed)
        r#"SELECT count(*) FROM demo.customers WHERE UNIQUE (SELECT u&"email" FROM demo.customers)"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" MATCH (SELECT u&"email" FROM demo.customers)"#,
        r#"SELECT count(*) FROM demo.customers WHERE (birth_date, birth_date) OVERLAPS (birth_date, u&"email"::date)"#,
        // XML extras
        r#"SELECT count(*) FROM demo.customers WHERE xmlcomment(u&"email") IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE xmlpi(name p, u&"email") IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE xmlroot(xmlelement(name e, u&"email"), version '1.0') IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE xmlconcat(xmlelement(name e, u&"email")) IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE xpath('//e', xmlelement(name e, u&"email")) IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE xml_is_well_formed(u&"email")"#,
        r#"SELECT count(*) FROM XMLTABLE(XMLNAMESPACES(u&"email" AS n), '/n:e' PASSING '<e/>' COLUMNS x text PATH '.')"#,
        // Whole-row extras
        r#"SELECT hstore(t.*) FROM demo.customers t"#,
        r#"SELECT jsonb_pretty(to_jsonb(t)) FROM demo.customers t"#,
        r#"SELECT jsonb_each(to_jsonb(t)) FROM demo.customers t"#,
        r#"SELECT * FROM demo.customers t, jsonb_each(to_jsonb(t))"#,
        r#"SELECT (jsonb_each(to_jsonb(t))).* FROM demo.customers t"#,
        r#"SELECT json_each_text(row_to_json(t)) FROM demo.customers t"#,
        r#"SELECT jsonb_object_keys(to_jsonb(t)) FROM demo.customers t"#,
        r#"SELECT t::json FROM demo.customers t"#,
        r#"SELECT t::jsonb FROM demo.customers t"#,
        r#"SELECT CAST(t AS jsonb) FROM demo.customers t"#,
        r#"SELECT ROW(t.*)::text FROM demo.customers t"#,
        r#"SELECT (t).*::text FROM demo.customers t"#,
        r#"SELECT demo.customers FROM demo.customers"#,
        r#"SELECT customers FROM demo.customers"#,
        r#"SELECT count(*) FROM demo.customers t WHERE (t).* IS NOT NULL"#,
        r#"SELECT * FROM json_populate_record(null::demo.customers, to_json(t)) FROM demo.customers t"#,
        r#"SELECT * FROM json_to_record(to_json(t)) AS x(id int, email text) FROM demo.customers t"#,
        r#"SELECT count(*) FROM demo.customers t WHERE t::demo.customers IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers t WHERE row_to_json(t)->>'email' = 'x'"#,
        r#"SELECT count(*) FROM demo.customers t WHERE to_jsonb(t) @> '{"email":"x"}'"#,
        r#"SELECT count(*) FROM demo.customers t WHERE jsonb_path_query_first(to_jsonb(t), '$.email') #>> '{}' = 'x'"#,
        // EXPLAIN wrappers around unicode predicates
        r#"EXPLAIN (ANALYZE false, COSTS false) SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'"#,
        r#"EXPLAIN (VERBOSE true) SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'"#,
        r#"EXPLAIN (FORMAT JSON) SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'"#,
        r#"EXPLAIN (GENERIC_PLAN) SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'"#,
        // Collation / domain / cstring
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" COLLATE "und-x-icu" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email"::cstring = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email"::name = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email"::varchar(32) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE CAST(u&"email" AS character varying) = 'x'"#,
        // GROUPING / FILTER / WITHIN GROUP extras
        r#"SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY u&"annual_salary") FROM demo.customers"#,
        r#"SELECT count(*) FILTER (WHERE u&"annual_salary" > 1) FROM demo.customers"#,
        r#"SELECT bool_or(u&"email" = 'x') FROM demo.customers"#,
        r#"SELECT bool_and(u&"email" <> 'x') FROM demo.customers"#,
        r#"SELECT every(u&"email" <> 'x') FROM demo.customers"#,
        // JSON_TABLE plan / passing
        r#"SELECT * FROM demo.customers, JSON_TABLE(u&"email", '$' COLUMNS (x text PATH '$')) jt"#,
        r#"SELECT * FROM JSON_TABLE((SELECT u&"email" FROM demo.customers LIMIT 1), '$' COLUMNS (x text PATH '$')) jt"#,
        // set-op with unicode on one side only
        r#"SELECT u&"email" FROM demo.customers INTERSECT SELECT 'x'"#,
        r#"SELECT u&"email" FROM demo.customers EXCEPT SELECT 'x'"#,
        r#"SELECT 'x' INTERSECT SELECT u&"email" FROM demo.customers"#,
        r#"SELECT u&"email" FROM demo.customers UNION ALL SELECT u&"name" FROM demo.customers"#,
        // CTE SEARCH / CYCLE extras
        r#"WITH RECURSIVE r AS (SELECT id, u&"email" FROM demo.customers UNION ALL SELECT id, email FROM r WHERE false)
           SEARCH DEPTH FIRST BY u&"email" SET ord CYCLE u&"email" SET is_cycle USING path SELECT count(*) FROM r"#,
        // Prefix mixed
        r#"SELECT count(*) FROM demo.customers WHERE U&"\0065mail" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"\0065mail" LIKE 'x%'"#,
        // Alias hiding via output name then filter (inner still names email)
        r#"SELECT count(*) FROM (SELECT u&"email" AS c2 FROM demo.customers) s WHERE c2 = 'x'"#,
        r#"SELECT count(*) FROM (SELECT u&"email" FROM demo.customers) s(c2) WHERE c2 = 'x'"#,
        // Whole-row in ARRAY constructor already; VARIADIC
        r#"SELECT format('%s', VARIADIC ARRAY[t::text]) FROM demo.customers t"#,
        // current of — needs cursor, still a ColumnRef?
        r#"SELECT count(*) FROM demo.customers WHERE CURRENT OF c"#,
        // Leaky catalogs (frontend, every posture)
        r#"SELECT most_common_vals FROM pg_stats"#,
        r#"SELECT most_common_vals FROM pg_catalog.pg_stats"#,
        r#"SELECT * FROM u&"pg_stats""#,
        r#"SELECT * FROM pg_catalog.u&"pg_stats""#,
        r#"SELECT query FROM pg_stat_activity"#,
        r#"SELECT * FROM u&"pg_stat_activity""#,
        r#"SELECT rolpassword FROM u&"pg_authid""#,
        r#"EXPLAIN SELECT most_common_vals FROM pg_stats"#,
        r#"EXPLAIN (ANALYZE true) SELECT query FROM pg_stat_activity"#,
        r#"EXPLAIN SELECT * FROM pg_catalog.pg_stats"#,
        r#"SELECT query FROM pg_stat_get_activity(NULL)"#,
        r#"SELECT * FROM pg_stat_get_activity(NULL) a"#,
        r#"SELECT * FROM pg_stat_statements()"#,
        r#"SELECT statement FROM pg_cursors"#,
        r#"SELECT * FROM pg_prepared_statements"#,
        r#"SELECT passwd FROM pg_user"#,
        r#"SELECT * FROM pg_user"#,
        r#"SELECT data FROM pg_largeobject"#,
        r#"SELECT stavalues1 FROM pg_statistic"#,
        r#"WITH s AS (SELECT * FROM pg_stats) SELECT * FROM s"#,
        r#"SELECT * FROM (SELECT * FROM pg_stats) s"#,
        r#"SELECT pg_read_file('/etc/passwd')"#,
        r#"SELECT query_to_xml('SELECT email FROM demo.customers', false, true, '')"#,
        // Writes still refuse
        r#"ANALYZE demo.customers"#,
        r#"VACUUM demo.customers"#,
        r#"REFRESH MATERIALIZED VIEW demo.v"#,
        r#"SELECT email INTO x FROM demo.customers"#,
        r#"SELECT email FROM demo.customers FOR UPDATE"#,
        r#"MERGE INTO demo.customers t USING demo.customers s ON t.id = s.id WHEN MATCHED THEN UPDATE SET city = s.city"#,
        r#"COPY demo.customers TO STDOUT"#,
        r#"LISTEN x"#,
        r#"LOAD 'auto_explain'"#,
        r#"SELECT CAST(1 AS numeric((SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'), 0))"#,
        r#"SELECT count(*) FROM demo.customers WHERE CAST(1 AS numeric((SELECT count(*) FROM demo.customers t2 WHERE t2.u&"email" = 'x'), 0)) IS NOT NULL"#,
        r#"SELECT JSON_VALUE('1', '$' RETURNING numeric((SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'), 0))"#,
        r#"SELECT JSON_QUERY('1', '$' RETURNING numeric((SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'), 0))"#,
        r#"SELECT count(*) FROM demo.customers WHERE JSON_VALUE('1', '$' RETURNING numeric((SELECT count(*) FROM demo.customers t2 WHERE t2.u&"email" = 'x'), 0)) IS NOT NULL"#,
        r#"EXPLAIN SELECT JSON_VALUE('1', '$' RETURNING numeric((SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'), 0))"#,
        r#"SELECT database_to_xml(true, true, '') FROM pg_catalog.pg_class"#,
        r#"SELECT schema_to_xml('demo', true, true, '') FROM pg_catalog.pg_class"#,
        r#"SELECT pg_stat_get_activity(NULL) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_ls_logdir() FROM pg_catalog.pg_class"#,
        r#"SELECT pg_logical_slot_get_changes('s', NULL, NULL) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_stat_get_wal_receiver() FROM pg_catalog.pg_class"#,
        r#"SELECT pg_stat_get_wal_receiver() FROM pg_catalog.pg_database"#,
        r#"SELECT crosstab('SELECT email FROM demo.customers') FROM pg_catalog.pg_class"#,
        r#"SELECT connectby('demo.customers','id','id','id','1',0) FROM pg_catalog.pg_class"#,
        r#"SELECT dblink_exec('dbname=x', 'SELECT 1') FROM pg_catalog.pg_class"#,
        r#"SELECT dblink_connect('dbname=x') FROM pg_catalog.pg_class"#,
        r#"SELECT pg_file_read('postgresql.conf', 0, 100) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_logdir_ls() FROM pg_catalog.pg_class"#,
        r#"SELECT loread(1, 100) FROM pg_catalog.pg_class"#,
        r#"SELECT lo_open(1, 262144) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_get_wal_records_info('0/0', '0/0') FROM pg_catalog.pg_class"#,
        r#"SELECT pg_get_wal_block_info('0/0', '0/0') FROM pg_catalog.pg_class"#,
        // Target-list FuncCall is an allowlist: unnamed dumps joined to
        // pg_class used to skip the untrusted-function gate.
        r#"SELECT get_raw_page('demo.customers'::regclass, 0) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_catalog.get_raw_page('demo.customers'::regclass, 0) FROM pg_catalog.pg_class"#,
        r#"SELECT u&"get_raw_page"('demo.customers'::regclass, 0) FROM pg_catalog.pg_class"#,
        r#"SELECT heap_page_items(get_raw_page('demo.customers'::regclass, 0)) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_sleep(0) FROM pg_catalog.pg_class"#,
        r#"SELECT set_config('application_name', 'x', false) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_file_write('x', 'y', false) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_terminate_backend(pg_backend_pid()) FROM pg_catalog.pg_class"#,
        r#"SELECT not_a_catalog_fn() FROM pg_catalog.pg_class"#,
        // TOAST heaps are the toasted bytes of user columns. Unqualified
        // pg_toast_* is catalog-shaped and skipped the leaky-name list.
        r#"SELECT chunk_data FROM pg_toast.pg_toast_12345"#,
        r#"SELECT count(*) FROM pg_toast.pg_toast_12345 WHERE chunk_data LIKE '%@%'"#,
        r#"SELECT * FROM pg_toast_12345"#,
        r#"SELECT * FROM pg_toast.pg_toast_12345_index"#,
        r#"SELECT * FROM u&"pg_toast".u&"pg_toast_12345""#,
        r#"EXPLAIN SELECT chunk_data FROM pg_toast.pg_toast_12345"#,
        r#"SELECT srvoptions FROM pg_catalog.pg_foreign_server"#,
        r#"SELECT fdwoptions FROM pg_foreign_data_wrapper"#,
        r#"SELECT * FROM u&"pg_foreign_server""#,
        r#"SELECT option_value FROM information_schema.user_mapping_options"#,
        r#"SELECT * FROM information_schema.foreign_server_options"#,
        r#"SELECT * FROM information_schema.foreign_data_wrapper_options"#,
        r#"SELECT * FROM information_schema.u&"user_mapping_options""#,
        r#"SELECT option_value FROM user_mapping_options"#,
        r#"EXPLAIN SELECT * FROM information_schema.user_mapping_options"#,
        r#"SELECT option_value FROM information_schema.column_options"#,
        r#"SELECT * FROM information_schema.foreign_table_options"#,
        r#"SELECT * FROM information_schema.u&"column_options""#,
        r#"SELECT option_value FROM column_options"#,
        r#"SELECT umoptions FROM information_schema._pg_user_mappings"#,
        r#"SELECT srvoptions FROM information_schema._pg_foreign_servers"#,
        r#"SELECT fdwoptions FROM information_schema._pg_foreign_data_wrappers"#,
        r#"SELECT ftoptions FROM information_schema._pg_foreign_tables"#,
        r#"SELECT attfdwoptions FROM information_schema._pg_foreign_table_columns"#,
        r#"SELECT umoptions FROM _pg_user_mappings"#,
        r#"SELECT * FROM information_schema.u&"_pg_user_mappings""#,
        r#"EXPLAIN SELECT * FROM information_schema.column_options"#,
        // Extra unicode frames that should already refuse
        r#"SELECT count(*) FROM demo.customers GROUP BY ROLLUP (u&"email")"#,
        r#"SELECT count(*) FROM demo.customers GROUP BY CUBE (u&"email")"#,
        r#"SELECT count(*) FROM demo.customers GROUP BY GROUPING SETS ((u&"email"))"#,
        r#"SELECT DISTINCT ON (u&"email") id FROM demo.customers"#,
        r#"SELECT count(*) FROM demo.customers WHERE (u&"email", city) = ('x', 'y')"#,
        r#"SELECT count(*) FROM demo.customers WHERE COALESCE(u&"email", 'x') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE NULLIF(u&"email", 'x') IS NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE GREATEST(u&"email", 'a') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" SIMILAR TO 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" NOT SIMILAR TO 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.~) 'x'"#,
        r#"SELECT count(*) FROM ONLY demo.customers WHERE u&"email" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers HAVING bool_or(u&"email" = 'x')"#,
        r#"SELECT id FROM demo.customers ORDER BY length(u&"email")"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" || '' = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE CASE WHEN u&"email" = 'x' THEN 1 ELSE 0 END = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON ARRAY"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON OBJECT"#,
        r#"SELECT count(*) FROM demo.customers WHERE normalize(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE starts_with(u&"email", 'x')"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" LIKE 'x%' ESCAPE '\'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" BETWEEN SYMMETRIC 'a' AND 'z'"#,
        r#"SELECT count(*) FROM demo.customers WHERE xmlexists('//x' PASSING BY REF u&"email")"#,
        r#"SELECT pg_read_binary_file('postgresql.conf') FROM pg_catalog.pg_class"#,
        r#"SELECT lo_from_bytea(0, 'x') FROM pg_catalog.pg_class"#,
        r#"SELECT pg_buffercache_pages() FROM pg_catalog.pg_class"#,
        r#"SELECT pg_stat_statements_reset() FROM pg_catalog.pg_class"#,
        r#"SELECT pg_log_backend_memory_contexts(pg_backend_pid()) FROM pg_catalog.pg_class"#,
        r#"SELECT pg_copy_logical_replication_slot('a','b') FROM pg_catalog.pg_class"#,
        r#"SELECT * FROM information_schema.u&"foreign_table_options""#,
        r#"SELECT * FROM information_schema.u&"_pg_foreign_servers""#,
        r#"SELECT * FROM information_schema._pg_foreign_future"#,
        r#"SELECT * FROM _pg_foreign_future"#,
    ];

    for sql in oracles {
        if !any_frontend_refuse(sql) {
            let parse_ok = pg_query::parse(sql).is_ok();
            bad.push(format!("OPEN (parse_ok={parse_ok}):\n  {sql}"));
        }
    }

    if !bad.is_empty() {
        panic!("{} finding(s):\n{}", bad.len(), bad.join("\n"));
    }
}

/// Second inventory: every information_schema view, core system views,
/// dump-function shapes, and unicode frames not in the list above.
/// Known residuals are asserted open; everything else must refuse.
#[test]
fn audit_catalog_and_sql_surface() {
    let mut bad = Vec::new();

    let option_views = [
        "user_mapping_options",
        "foreign_server_options",
        "foreign_data_wrapper_options",
        "column_options",
        "foreign_table_options",
        "_pg_user_mappings",
        "_pg_foreign_servers",
        "_pg_foreign_data_wrappers",
        "_pg_foreign_tables",
        "_pg_foreign_table_columns",
    ];
    for name in option_views {
        for sql in [
            format!("SELECT * FROM information_schema.{name}"),
            format!("SELECT * FROM {name}"),
        ] {
            if !touches_leaky_system_catalog(&sql) {
                bad.push(format!("option view not leaky: {sql}"));
            }
        }
    }

    // Name-only / schema IS views. Must stay metadata-only so GUIs work.
    for name in [
        "tables",
        "columns",
        "views",
        "routines",
        "schemata",
        "sequences",
        "user_mappings",
        "foreign_servers",
        "foreign_tables",
        "foreign_data_wrappers",
        "parameters",
        "triggers",
        "check_constraints",
        "table_constraints",
        "key_column_usage",
        "applicable_roles",
        "enabled_roles",
        "character_sets",
        "collations",
        "domains",
        "user_defined_types",
        "attributes",
        "element_types",
        "data_type_privileges",
        "role_table_grants",
        "role_column_grants",
        "role_routine_grants",
        "role_udt_grants",
        "role_usage_grants",
        "usage_privileges",
        "udt_privileges",
        "table_privileges",
        "column_privileges",
        "routine_privileges",
        "information_schema_catalog_name",
    ] {
        let sql = format!("SELECT * FROM information_schema.{name}");
        if touches_leaky_system_catalog(&sql) {
            bad.push(format!("over-refused IS view: {sql}"));
        }
        if !reads_only_server_metadata(&sql) {
            bad.push(format!("IS view not metadata-only: {sql}"));
        }
    }

    // Core catalogs that carry values / secrets / SQL text.
    for sql in [
        "SELECT * FROM pg_catalog.pg_statistic",
        "SELECT * FROM pg_catalog.pg_stats",
        "SELECT * FROM pg_catalog.pg_authid",
        "SELECT * FROM pg_catalog.pg_shadow",
        "SELECT * FROM pg_catalog.pg_user",
        "SELECT * FROM pg_catalog.pg_stat_activity",
        "SELECT * FROM pg_catalog.pg_stat_statements",
        "SELECT * FROM pg_catalog.pg_prepared_statements",
        "SELECT * FROM pg_catalog.pg_cursors",
        "SELECT * FROM pg_catalog.pg_stat_wal_receiver",
        "SELECT * FROM pg_catalog.pg_stat_monitor",
        "SELECT query FROM pg_stat_monitor",
        r#"SELECT * FROM u&"pg_stat_monitor""#,
        "SELECT constvalue FROM pg_qualstats",
        "SELECT plan FROM pg_store_plans",
        "SELECT * FROM pg_stat_kcache",
        "SELECT * FROM pg_stat_unknown_dump",
        "SELECT * FROM pg_show_plans",
        "SELECT query FROM pg_catalog.pg_show_plans",
        r#"SELECT * FROM u&"pg_show_plans""#,
        "EXPLAIN SELECT * FROM pg_show_plans",
        "SELECT * FROM pg_query_state",
        r#"SELECT * FROM u&"pg_query_state""#,
        "SELECT query FROM pg_catalog.citus_stat_activity",
        "SELECT * FROM citus_stat_activity",
        "SELECT query FROM pg_catalog.citus_stat_statements",
        "SELECT * FROM pg_catalog.citus_lock_waits",
        "SELECT blocked_statement FROM citus_lock_waits",
        r#"SELECT * FROM u&"citus_lock_waits""#,
        "EXPLAIN SELECT * FROM pg_catalog.citus_lock_waits",
        "SELECT tenant_attribute FROM pg_catalog.citus_stat_tenants",
        "SELECT authinfo FROM pg_catalog.pg_dist_authinfo",
        "SELECT * FROM pg_dist_authinfo",
        r#"SELECT * FROM u&"pg_dist_authinfo""#,
        "SELECT poolinfo FROM pg_dist_poolinfo",
        "SELECT command FROM pg_dist_background_task",
        "SELECT shardminvalue FROM pg_dist_shard",
        "SELECT * FROM pg_catalog.pg_largeobject",
        "SELECT * FROM pg_catalog.pg_user_mapping",
        "SELECT * FROM pg_catalog.pg_user_mappings",
        "SELECT * FROM pg_catalog.pg_subscription",
        "SELECT * FROM pg_catalog.pg_foreign_server",
        "SELECT * FROM pg_catalog.pg_foreign_data_wrapper",
        "SELECT * FROM pg_catalog.pg_file_settings",
        "SELECT * FROM pg_catalog.pg_hba_file_rules",
        "SELECT * FROM pg_catalog.pg_ident_file_mappings",
        "SELECT * FROM pg_catalog.pg_backend_memory_contexts",
        "SELECT * FROM pg_catalog.pg_statistic_ext_data",
        "SELECT * FROM pg_catalog.pg_stats_ext",
        "SELECT * FROM pg_catalog.pg_stats_ext_exprs",
        "SELECT * FROM pg_stat_activity",
        "SELECT * FROM pg_stats",
        r#"SELECT * FROM u&"pg_stats""#,
        "TABLE pg_catalog.pg_stats",
        "SELECT * FROM pg_stat_get_activity(NULL)",
        "SELECT * FROM pg_stat_statements()",
        "SELECT pg_stat_statements(true) FROM pg_catalog.pg_class",
        "SELECT pg_mcv_list_items(stxdmcv) FROM pg_catalog.pg_statistic_ext_data",
        "SELECT * FROM pg_options_to_table((SELECT umoptions FROM pg_user_mapping LIMIT 1))",
        "SELECT lo_get(loid) FROM pg_largeobject_metadata",
        "SELECT encode(lo_get(1), 'escape') FROM pg_catalog.pg_class",
        "SELECT * FROM dblink('dbname=x', 'SELECT 1')",
        "SELECT * FROM crosstab('SELECT 1')",
        "SELECT * FROM heap_page_items(get_raw_page('demo.customers'::regclass, 0))",
        "SELECT pg_stat_get_backend_activity(1) FROM generate_series(1,1) g, pg_catalog.pg_class c",
        "SELECT postgres_fdw_get_connections() FROM pg_catalog.pg_class",
        "SELECT pg_walinspect.pg_get_wal_record_info('0/0') FROM pg_catalog.pg_class",
        "SELECT xpath_table('n','d','t','p','w') FROM pg_catalog.pg_class",
        "SELECT pgp_sym_decrypt('x'::bytea, 'k') FROM pg_catalog.pg_class",
        "SELECT decrypt('x'::bytea, 'k'::bytea, 'aes') FROM pg_catalog.pg_class",
        "SELECT pg_read_file(pg_current_logfile()) FROM pg_catalog.pg_class",
        "SELECT pg_ls_replslotdir() FROM pg_catalog.pg_class",
        "SELECT pg_stat_get_backend_io(1) FROM pg_catalog.pg_class",
    ] {
        if !any_frontend_refuse(sql) {
            bad.push(format!("OPEN catalog/dump:\n  {sql}"));
        }
    }

    // Must stay allowed: GUI / psql / name-only catalogs, SHOW, residual \d.
    for sql in [
        "SELECT rolname FROM pg_roles",
        "SELECT * FROM pg_catalog.pg_class",
        "SELECT * FROM pg_catalog.pg_attribute",
        "SELECT * FROM pg_catalog.pg_proc",
        "SELECT * FROM pg_catalog.pg_type",
        "SELECT * FROM pg_catalog.pg_namespace",
        "SELECT * FROM pg_catalog.pg_index",
        "SELECT * FROM pg_catalog.pg_constraint",
        "SELECT * FROM pg_catalog.pg_attrdef",
        "SELECT * FROM pg_catalog.pg_rewrite",
        "SELECT * FROM pg_catalog.pg_trigger",
        "SELECT * FROM pg_catalog.pg_policy",
        "SELECT * FROM pg_catalog.pg_statistic_ext",
        "SELECT * FROM pg_catalog.pg_foreign_table",
        "SELECT attfdwoptions FROM pg_catalog.pg_attribute",
        "SELECT ftoptions FROM pg_catalog.pg_foreign_table",
        "SELECT * FROM pg_catalog.pg_largeobject_metadata",
        "SELECT * FROM pg_catalog.pg_roles",
        "SELECT * FROM pg_catalog.pg_settings",
        "SELECT * FROM pg_catalog.pg_db_role_setting",
        "SELECT * FROM pg_catalog.pg_stat_user_tables",
        "SELECT * FROM pg_catalog.pg_stat_all_tables",
        "SELECT * FROM pg_catalog.pg_stat_replication",
        "SELECT * FROM pg_catalog.pg_stat_ssl",
        "SELECT * FROM pg_catalog.pg_stat_gssapi",
        "SELECT * FROM pg_catalog.pg_stat_subscription",
        "SELECT * FROM pg_catalog.pg_stat_subscription_stats",
        "SELECT * FROM pg_catalog.pg_stat_statements_info",
        "SELECT * FROM pg_catalog.pg_stat_progress_copy",
        "SELECT * FROM pg_catalog.pg_stat_progress_vacuum",
        "SELECT * FROM pg_catalog.pg_locks",
        "SELECT * FROM pg_catalog.pg_views",
        "SELECT * FROM pg_catalog.pg_indexes",
        "SELECT * FROM pg_catalog.pg_tables",
        "SELECT * FROM pg_catalog.pg_sequences",
        "SELECT * FROM pg_catalog.pg_matviews",
        "SELECT * FROM pg_catalog.pg_rules",
        "SELECT * FROM pg_catalog.pg_seclabels",
        "SELECT * FROM pg_catalog.pg_group",
        "SELECT * FROM pg_catalog.pg_config",
        "SELECT * FROM pg_catalog.pg_available_extensions",
        "SELECT * FROM pg_catalog.pg_prepared_xacts",
        "SELECT * FROM pg_catalog.pg_replication_slots",
        "SELECT * FROM pg_catalog.pg_replication_origin_status",
        "SELECT * FROM pg_catalog.pg_shmem_allocations",
        "SELECT * FROM pg_catalog.pg_timezone_names",
        "SELECT * FROM pg_catalog.pg_stat_database",
        "SELECT * FROM pg_catalog.pg_stat_bgwriter",
        "SELECT * FROM pg_catalog.pg_stat_checkpointer",
        "SELECT * FROM pg_catalog.pg_stat_io",
        "SELECT * FROM pg_catalog.pg_stat_wal",
        "SELECT * FROM pg_catalog.pg_wait_events",
        "SELECT * FROM pg_catalog.pg_aios",
        "SELECT * FROM pg_catalog.pg_buffercache",
        "SELECT * FROM pg_catalog.pg_statio_user_tables",
        "SELECT * FROM pg_wait_sampling_profile",
        "SHOW all",
        "SHOW primary_conninfo",
        "SET ROLE analyst",
        "DISCARD ALL",
        "SELECT current_setting('search_path') FROM pg_catalog.pg_class",
        r#"SELECT u&"email" FROM demo.customers GROUP BY 1 HAVING count(*) > 0"#,
        r#"SELECT DISTINCT u&"email" FROM demo.customers WHERE city = 'x'"#,
        "SELECT count(*) FROM demo.customers LIMIT ALL",
        r#"SELECT id FROM demo.customers ORDER BY u&"email" USING OPERATOR(pg_catalog.=)"#,
    ] {
        if any_frontend_refuse(sql) {
            bad.push(format!("over-refused residual:\n  {sql}"));
        }
    }

    let extra_oracles: &[&str] = &[
        r#"SELECT (t).u&"email" FROM demo.customers t"#,
        r#"SELECT count(*) FROM demo.customers t WHERE (t).u&"email" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers t WHERE t = t"#,
        r#"SELECT count(*) FROM demo.customers t WHERE ROW(t.*) IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers t WHERE t IN (SELECT t FROM demo.customers)"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" NOT BETWEEN 'a' AND 'z'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" NOT IN ('x')"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" = SOME (VALUES ('x'))"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" = ANY (VALUES ('x'))"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.=) ALL (SELECT 'x')"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" ~~ ANY (ARRAY['x%'])"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" LIKE ALL (VALUES ('x%'))"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" ILIKE 'x' ESCAPE '#'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON ARRAY WITH UNIQUE KEYS"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON OBJECT WITHOUT UNIQUE KEYS"#,
        r#"SELECT count(*) FROM demo.customers WHERE CAST(u&"email" AS name) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE (u&"email") COLLATE "C" LIKE 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS DISTINCT FROM 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS NOT DISTINCT FROM u&"name""#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" NOT LIKE 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" NOT ILIKE 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" ~* 'x'"#,
        r#"SELECT count(*) FROM demo.customers t WHERE (t).* IS NOT DISTINCT FROM (t).*"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" = ALL (ARRAY['x'])"#,
        r#"SELECT count(*) FROM demo.customers WHERE TRIM(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" SIMILAR TO 'x%' ESCAPE '#'"#,
        r#"SELECT count(*) FROM demo.customers WHERE POSITION('x' IN u&"email") = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" BETWEEN SYMMETRIC 'z' AND 'a'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"annual_salary" * 1 > 0"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"annual_salary" / 1 > 0"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"annual_salary" % 2 = 0"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"annual_salary" ^ 1 = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE @ u&"annual_salary" > 0"#,
        r#"SELECT count(*) FROM demo.customers WHERE |/ u&"annual_salary" > 0"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" || u&"name" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE EXISTS (SELECT 1 FROM demo.customers t2 WHERE t2.u&"email" = demo.customers.u&"email")"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IN (SELECT u&"email" FROM demo.customers)"#,
        r#"SELECT count(*) FROM demo.customers WHERE (SELECT u&"email" FROM demo.customers LIMIT 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" = (SELECT 'x')"#,
        r#"WITH x AS (SELECT u&"email" FROM demo.customers) SELECT count(*) FROM x WHERE email = 'x'"#,
        r#"SELECT count(*) FROM (SELECT u&"email" FROM demo.customers) q WHERE q.email = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE CASE u&"email" WHEN 'x' THEN 1 ELSE 0 END = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS NOT NULL AND u&"email" = 'x'"#,
        r#"SELECT json_object(u&"email", city) FROM demo.customers"#,
        r#"SELECT jsonb_build_object('e', u&"email") FROM demo.customers"#,
        r#"SELECT to_jsonb(u&"email") FROM demo.customers"#,
        r#"SELECT array_agg(u&"email") FROM demo.customers"#,
        r#"SELECT string_agg(u&"email", ',') FROM demo.customers"#,
        r#"SELECT bool_or(u&"email" IS NOT NULL) FROM demo.customers"#,
        r#"SELECT mode() WITHIN GROUP (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT rank() OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT ntile(2) OVER (PARTITION BY u&"email") FROM demo.customers"#,
        r#"SELECT lag(city) OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT count(*) FROM demo.customers TABLESAMPLE SYSTEM (1) REPEATABLE (ascii(u&"email"))"#,
        r#"SELECT count(*) FROM demo.customers AS t(c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11)"#,
        r#"SELECT * FROM demo.customers t(c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11)"#,
        r#"COPY (SELECT count(*) FROM demo.customers WHERE u&"email" = 'x') TO STDOUT"#,
        r#"MERGE INTO demo.customers t USING demo.customers s ON t.u&"email" = s.u&"email" WHEN MATCHED THEN DELETE"#,
        r#"DO $$ BEGIN PERFORM count(*) FROM demo.customers WHERE email = 'x'; END $$"#,
        r#"CALL demo.do_thing(u&"email")"#,
        r#"SELECT * FROM XMLTABLE('/e' PASSING xmlelement(name e, u&"email") COLUMNS x text PATH '.')"#,
        r#"SELECT JSON_TABLE(u&"email", '$' COLUMNS (x text PATH '$')) FROM demo.customers"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.=) 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.<>) 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS UNKNOWN"#,
        r#"SELECT count(*) FROM demo.customers WHERE NOT (u&"email" = 'x')"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS NOT TRUE"#,
        r#"SELECT pg_notify('c', u&"email") FROM demo.customers"#,
        r#"SELECT * FROM regexp_split_to_table((SELECT u&"email" FROM demo.customers LIMIT 1), '@')"#,
        r#"SELECT * FROM unnest((SELECT ARRAY[u&"email"] FROM demo.customers LIMIT 1))"#,
        r#"SELECT count(*) FROM demo.customers, LATERAL (SELECT u&"email") s(e) WHERE s.e = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email"::bytea = 'x'::bytea"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email"::jsonb ? 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE to_timestamp(u&"email", 'YYYY') IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE md5(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE sha256(u&"email"::bytea) = sha256('x'::bytea)"#,
        r#"SELECT count(*) FROM demo.customers WHERE length(convert_to(u&"email", 'UTF8')) = 5"#,
        r#"SELECT count(*) FROM demo.customers WHERE encode(u&"email"::bytea, 'hex') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE decode(encode(u&"email"::bytea, 'hex'), 'hex') = 'x'::bytea"#,
        r#"EXPLAIN ANALYZE SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'"#,
        r#"EXPLAIN (ANALYZE, BUFFERS) SELECT count(*) FROM demo.customers WHERE u&"email" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" ~ 'x' COLLATE "C""#,
        r#"SELECT count(*) FROM demo.customers GROUP BY u&"email""#,
        r#"SELECT count(DISTINCT u&"email") FROM demo.customers"#,
        r#"SELECT percentile_disc(0.5) WITHIN GROUP (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT * FROM demo.customers FOR UPDATE"#,
        r#"SELECT * FROM demo.customers FOR SHARE OF demo.customers"#,
        r#"SELECT * FROM demo.customers FOR NO KEY UPDATE"#,
        r#"SELECT * FROM demo.customers FOR KEY SHARE"#,
        r#"SELECT count(*) FROM ONLY demo.customers WHERE u&"phone" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"internal_note" LIKE '%x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"name" || '' LIKE 'A%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE lower(u&"name") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE upper(u&"name") = 'X'"#,
        r#"SELECT count(*) FROM demo.customers WHERE initcap(u&"name") = 'X'"#,
        r#"SELECT count(*) FROM demo.customers WHERE left(u&"email", 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE right(u&"email", 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE split_part(u&"email", '@', 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE to_char(u&"annual_salary", '999') = '1'"#,
        r#"SELECT count(*) FROM demo.customers WHERE to_number(u&"email", '999') = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE format('%s', u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE concat(u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE concat_ws(',', u&"email") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE overlay(u&"email" placing 'x' from 1 for 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE substring(u&"email" from 1 for 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE substr(u&"email" from 1 for 1) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" LIKE 'x' ESCAPE (SELECT '#' FROM demo.customers t2 WHERE t2.u&"email" = 'y' LIMIT 1)"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" BETWEEN (SELECT 'a') AND (SELECT 'z')"#,
        r#"SELECT 1 FROM demo.customers WHERE u&"email" = 'x' UNION SELECT 1"#,
        r#"SELECT 1 FROM demo.customers WHERE u&"email" = 'x' INTERSECT SELECT 1"#,
        r#"SELECT 1 FROM demo.customers WHERE u&"email" = 'x' EXCEPT SELECT 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" = 'x' FETCH FIRST 1 ROW ONLY"#,
        r#"SELECT count(*) FROM demo.customers OFFSET (SELECT count(*) FROM demo.customers t2 WHERE t2.u&"email" = 'x')"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS NULL OR u&"email" = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE COALESCE(NULLIF(u&"email", ''), 'x') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE GREATEST(u&"email", u&"name") = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE LEAST(u&"email", 'x') = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE WIDTH_BUCKET(u&"annual_salary", 0, 1, 10) = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE num_nonnulls(u&"email") = 1"#,
        r#"SELECT count(*) FROM demo.customers WHERE num_nulls(u&"email") = 0"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS NOT DISTINCT FROM NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE ROW(u&"email") IS NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE ROW(u&"email", city) IS NOT NULL"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" = u&"email""#,
        r#"SELECT pg_typeof(u&"email") FROM demo.customers"#,
        r#"SELECT pg_column_size(u&"email") FROM demo.customers"#,
        r#"SELECT octet_length(u&"email") FROM demo.customers"#,
        r#"SELECT ascii(u&"email") FROM demo.customers"#,
        r#"SELECT hashtextextended(u&"email", 0) FROM demo.customers"#,
        r#"SELECT json_agg(u&"email") FROM demo.customers"#,
        r#"SELECT jsonb_agg(u&"email" ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT xmlagg(xmlelement(name e, u&"email")) FROM demo.customers"#,
        r#"SELECT COUNT(*) FILTER (WHERE u&"email" = 'x') FROM demo.customers"#,
        r#"SELECT COUNT(u&"email") FROM demo.customers"#,
        r#"SELECT MAX(u&"email") FROM demo.customers"#,
        r#"SELECT MIN(u&"email") FROM demo.customers"#,
        r#"SELECT SUM(length(u&"email")) FROM demo.customers"#,
        r#"SELECT AVG(u&"annual_salary") FROM demo.customers"#,
        r#"SELECT VAR_POP(u&"annual_salary") FROM demo.customers"#,
        r#"SELECT STDDEV_POP(u&"annual_salary") FROM demo.customers"#,
        r#"SELECT CORR(u&"annual_salary", u&"annual_salary") FROM demo.customers"#,
        r#"SELECT regr_slope(u&"annual_salary", u&"annual_salary") FROM demo.customers"#,
        r#"SELECT grouping(u&"email") FROM demo.customers GROUP BY ROLLUP (u&"email")"#,
        r#"SELECT JSON_EXISTS(u&"email", '$')"#,
        r#"SELECT JSON_VALUE(u&"email", '$')"#,
        r#"SELECT JSON_QUERY(u&"email", '$')"#,
        r#"SELECT JSON_SERIALIZE(u&"email")"#,
        r#"SELECT JSON_SCALAR(u&"email")"#,
        r#"SELECT JSON_PARSE(u&"email")"#,
        r#"SELECT * FROM JSON_TABLE('[]', '$[*]' COLUMNS (x int PATH '$' DEFAULT (SELECT count(*) FROM demo.customers WHERE u&"email" = 'x') ON EMPTY))"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IS JSON WITH UNIQUE KEYS AND u&"email" IS JSON"#,
        r#"SELECT count(*) FROM demo.customers WHERE starts_with(u&"email", 'u')"#,
        r#"SELECT count(*) FROM demo.customers WHERE unicode_is_normalized(u&"email")"#,
        r#"SELECT count(*) FROM demo.customers WHERE unicode_assigned(u&"email")"#,
        r#"SELECT count(*) FROM demo.customers WHERE normalize(u&"email", NFC) = 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE IS_NORMALIZED(u&"email")"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" COLLATE "und-x-icu" > 'a'"#,
        r#"SELECT * FROM demo.customers WHERE u&"email" = 'x' ORDER BY id"#,
        r#"SELECT id FROM demo.customers ORDER BY u&"email" = 'x'"#,
        r#"SELECT id FROM demo.customers WINDOW w AS (PARTITION BY u&"email")"#,
        r#"SELECT id, first_value(city) OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT id, last_value(city) OVER (ORDER BY u&"email" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM demo.customers"#,
        r#"SELECT id, nth_value(city, 1) OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT id, cume_dist() OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT id, percent_rank() OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT id, dense_rank() OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT id, row_number() OVER (ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT * FROM (VALUES ((SELECT u&"email" FROM demo.customers LIMIT 1))) v(e)"#,
        r#"SELECT * FROM (SELECT * FROM demo.customers) AS t(a,b,c,d,e,f,g,h,i,j,k)"#,
        r#"WITH q(a,b,c,d,e,f,g,h,i,j,k) AS (SELECT * FROM demo.customers) SELECT * FROM q"#,
        r#"SELECT * FROM demo.customers NATURAL JOIN demo.customers b"#,
        r#"SELECT count(*) FROM demo.customers a JOIN demo.customers b USING (u&"email")"#,
        r#"SELECT count(*) FROM demo.customers a JOIN demo.customers b ON a.u&"phone" = b.u&"phone""#,
        r#"SELECT count(*) FROM demo.customers a LEFT JOIN demo.customers b ON a.u&"email" IS NOT DISTINCT FROM b.u&"email""#,
        r#"SELECT count(*) FROM demo.customers a RIGHT JOIN demo.customers b ON a.u&"name" = b.u&"name""#,
        r#"SELECT count(*) FROM demo.customers a FULL JOIN demo.customers b ON a.u&"internal_note" = b.u&"internal_note""#,
        r#"SELECT count(*) FROM demo.customers a CROSS JOIN LATERAL (SELECT a.u&"email") s"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" IN (VALUES ('x'), ('y'))"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" MATCH SIMPLE (SELECT u&"email" FROM demo.customers)"#,
        r#"SELECT count(*) FROM demo.customers WHERE UNIQUE (SELECT u&"email" FROM demo.customers t2 WHERE t2.id = demo.customers.id)"#,
        r#"SELECT count(*) FROM demo.customers WHERE xmlexists('//x[.=$e]' PASSING BY REF '<x/>', BY VALUE u&"email" AS e)"#,
        r#"SELECT xpath('//e/text()', xmlelement(name e, u&"email")) FROM demo.customers"#,
        r#"SELECT xmlforest(u&"email" AS e) FROM demo.customers"#,
        r#"SELECT xmlelement(name e, xmlattributes(u&"email" AS a)) FROM demo.customers"#,
        r#"SELECT xmlparse(content u&"email") FROM demo.customers"#,
        r#"SELECT xmlparse(document u&"email") FROM demo.customers"#,
        r#"SELECT xmlserialize(content xmlelement(name e, u&"email") AS text) FROM demo.customers"#,
        r#"SELECT xmlpi(name php, u&"email") FROM demo.customers"#,
        r#"SELECT xmlroot(xmlelement(name e, u&"email"), version no value) FROM demo.customers"#,
        r#"SELECT xmlagg(u&"email"::xml ORDER BY u&"email") FROM demo.customers"#,
        r#"SELECT * FROM pg_catalog.pg_stat_activity WHERE query LIKE '%email%'"#,
        r#"SELECT query FROM pg_stat_statements WHERE query LIKE '%@%'"#,
        r#"SELECT most_common_vals FROM pg_stats WHERE attname = 'email'"#,
        r#"SELECT * FROM pg_toast.pg_toast_2619"#,
        r#"SELECT * FROM pg_catalog.pg_authid WHERE rolpassword IS NOT NULL"#,
        r#"SELECT pg_read_binary_file(pg_relation_filepath('demo.customers'::regclass), 0, 8192) FROM pg_catalog.pg_class"#,
        r#"SELECT convert_from(pg_read_binary_file('base/1/1', 0, 8), 'UTF8') FROM pg_catalog.pg_class"#,
        r#"SELECT * FROM pg_ls_dir('.', true, true)"#,
        r#"SELECT * FROM pg_logdir_ls()"#,
        r#"SELECT * FROM pg_ls_tmpdir()"#,
        r#"SELECT * FROM pg_ls_waldir()"#,
        r#"SELECT * FROM pg_ls_logicalmapdir()"#,
        r#"SELECT * FROM pg_ls_logicalsnapdir()"#,
        r#"SELECT * FROM pg_ls_summariesdir()"#,
        r#"SELECT * FROM pg_ls_archive_statusdir()"#,
        r#"SELECT * FROM pg_stat_file('postgresql.conf')"#,
        r#"SELECT * FROM lo_get(1)"#,
        r#"SELECT * FROM pg_logical_slot_peek_changes('s', NULL, NULL)"#,
        r#"SELECT * FROM pg_logical_slot_get_binary_changes('s', NULL, NULL)"#,
        r#"SELECT * FROM pg_get_wal_records_info('0/0', '0/0')"#,
        r#"SELECT * FROM connectby('demo.customers','id','id','id','1',0)"#,
        r#"SELECT * FROM crosstab2('SELECT 1')"#,
        r#"SELECT * FROM dblink_exec('x','SELECT 1')"#,
        r#"SELECT query_to_xml('SELECT 1', false, true, '')"#,
        r#"SELECT table_to_xmlschema('demo.customers'::regclass, false, true, '')"#,
        r#"SELECT cursor_to_xml('c'::refcursor, 1, false, true, '')"#,
        r#"SELECT schema_to_xml_and_xmlschema('demo', false, true, '')"#,
        r#"SELECT database_to_xmlschema(false, true, '')"#,
        r#"SELECT pg_stat_get_wal_receiver() FROM pg_catalog.pg_database"#,
        r#"SELECT pg_stat_get_activity(pid) FROM pg_catalog.pg_stat_activity"#,
        r#"SELECT * FROM pg_catalog.pg_stat_wal_receiver"#,
        r#"SELECT conninfo FROM pg_stat_wal_receiver"#,
        r#"SELECT umoptions FROM pg_user_mapping"#,
        r#"SELECT srvoptions FROM pg_foreign_server"#,
        r#"SELECT fdwoptions FROM pg_foreign_data_wrapper"#,
        r#"SELECT subconninfo FROM pg_subscription"#,
        r#"SELECT statement FROM pg_prepared_statements"#,
        r#"SELECT statement FROM pg_cursors"#,
        r#"SELECT query FROM pg_stat_activity"#,
        r#"SELECT passwd FROM pg_shadow"#,
        r#"SELECT rolpassword FROM pg_authid"#,
        r#"SELECT data FROM pg_largeobject"#,
        r#"SELECT chunk_data FROM pg_toast_12345"#,
        r#"SELECT setting FROM pg_file_settings"#,
        r#"SELECT * FROM pg_hba_file_rules"#,
        r#"SELECT * FROM pg_ident_file_mappings"#,
        r#"SELECT * FROM pg_backend_memory_contexts"#,
        r#"SELECT stavalues1 FROM pg_statistic"#,
        r#"SELECT stxdmcv FROM pg_statistic_ext_data"#,
        r#"SELECT histogram_bounds FROM pg_stats_ext"#,
        r#"SELECT exprvalues FROM pg_stats_ext_exprs"#,
        r#"SELECT * FROM information_schema.column_options"#,
        r#"SELECT * FROM information_schema.foreign_table_options"#,
        r#"SELECT * FROM information_schema._pg_user_mappings"#,
        r#"SELECT * FROM information_schema._pg_foreign_table_columns"#,
        r#"SELECT * FROM information_schema._pg_foreign_tables"#,
        r#"SELECT * FROM information_schema._pg_foreign_servers"#,
        r#"SELECT * FROM information_schema._pg_foreign_data_wrappers"#,
        r#"SELECT option_value FROM column_options"#,
        r#"SELECT option_value FROM foreign_table_options"#,
        r#"SELECT umoptions FROM _pg_user_mappings"#,
        r#"SELECT * FROM pg_catalog.u&"pg_stat_activity""#,
        r#"SELECT * FROM pg_catalog.u&"pg_stats""#,
        r#"SELECT * FROM u&"information_schema".u&"user_mapping_options""#,
        r#"EXPLAIN SELECT * FROM pg_stats"#,
        r#"EXPLAIN SELECT * FROM information_schema.column_options"#,
        r#"SELECT * FROM pg_toast.pg_toast_12345_index"#,
        r#"SELECT * FROM pg_toast.anything"#,
        r#"SET search_path TO pg_toast; SELECT * FROM pg_toast_12345"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.~~) 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.~~*) 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.!~~) 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.!~~*) 'x%'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.~) 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.~*) 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.!~) 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" OPERATOR(pg_catalog.!~*) 'x'"#,
        r#"SELECT count(*) FROM demo.customers WHERE u&"email" AT LOCAL IS NOT NULL"#,
        r#"SELECT * FROM ts_stat('SELECT u&"email" FROM demo.customers')"#,
        r#"SELECT ts_stat('SELECT to_tsvector(u&"email") FROM demo.customers') FROM pg_catalog.pg_class"#,
        r#"SELECT * FROM pg_stat_monitor"#,
        r#"SELECT query FROM pg_catalog.pg_stat_monitor"#,
        r#"SELECT constvalue FROM pg_qualstats"#,
        r#"SELECT plan FROM pg_store_plans"#,
        r#"SELECT * FROM pg_stat_unknown_dump"#,
        r#"SELECT * FROM pg_show_plans"#,
        r#"SELECT query FROM pg_catalog.pg_show_plans"#,
        r#"SELECT * FROM u&"pg_show_plans""#,
        r#"EXPLAIN SELECT * FROM pg_show_plans"#,
        r#"SELECT * FROM pg_query_state"#,
        r#"SELECT * FROM pg_catalog.pg_query_state"#,
        r#"SELECT * FROM u&"pg_query_state""#,
        r#"SELECT query FROM pg_catalog.citus_stat_activity"#,
        r#"SELECT * FROM citus_stat_activity"#,
        r#"SELECT query FROM edb_stat_activity"#,
        r#"SELECT query FROM pg_catalog.citus_stat_statements"#,
        r#"SELECT * FROM pg_catalog.citus_lock_waits"#,
        r#"SELECT blocked_statement FROM citus_lock_waits"#,
        r#"SELECT * FROM u&"citus_lock_waits""#,
        r#"EXPLAIN SELECT * FROM pg_catalog.citus_lock_waits"#,
        r#"SELECT tenant_attribute FROM pg_catalog.citus_stat_tenants"#,
        r#"SELECT * FROM citus_stat_tenants"#,
        r#"SELECT authinfo FROM pg_catalog.pg_dist_authinfo"#,
        r#"SELECT * FROM pg_dist_authinfo"#,
        r#"SELECT * FROM u&"pg_dist_authinfo""#,
        r#"SELECT poolinfo FROM pg_dist_poolinfo"#,
        r#"SELECT command FROM pg_dist_background_task"#,
        r#"SELECT shardminvalue FROM pg_catalog.pg_dist_shard"#,
        r#"EXPLAIN SELECT authinfo FROM pg_dist_authinfo"#,
    ];

    for sql in extra_oracles {
        if !any_frontend_refuse(sql) {
            let parse_ok = pg_query::parse(sql).is_ok();
            bad.push(format!("OPEN (parse_ok={parse_ok}):\n  {sql}"));
        }
    }

    if !bad.is_empty() {
        panic!("{} finding(s):\n{}", bad.len(), bad.join("\n"));
    }
}
